(function(){'use strict';var root=document.getElementById('legislativo-public-panel');if(!root)return;var id=root.dataset.sessionId;var timerState=null;var eventId='';var loading=false;
	function el(tag,cls,text){var n=document.createElement(tag);if(cls)n.className=cls;if(typeof text!=='undefined')n.textContent=text;return n;}
	function status(value){return{scheduled:'Agendada',open:'Em andamento',closed:'Encerrada',pending:'Aguardando',voting:'Votação aberta'}[value]||value;}
	function tally(t){if(!t)return'Sem votos';if(typeof t.yes==='undefined')return t.total+' voto(s) secreto(s) computado(s)';return'Sim '+t.yes+' · Não '+t.no+' · Abstenção '+t.abstain+' · Obstrução '+t.obstruction;}
	function render(data){var s=data.session;document.getElementById('panel-session').textContent=s.type+' nº '+s.number+'/'+s.year;document.getElementById('panel-status').textContent=status(s.status);document.getElementById('panel-presence').textContent=s.presentCount+' / '+s.totalSeats;timerState={status:s.timerStatus,label:s.timerLabel,started:s.timerStartedAt,duration:s.timerDuration,server:new Date(s.serverTime).getTime(),received:Date.now()};document.getElementById('panel-timer-label').textContent=s.timerLabel||'Cronômetro';
		var agenda=document.getElementById('panel-agenda');agenda.replaceChildren();(data.agenda||[]).forEach(function(item){var card=el('article','panel-ballot '+(item.status==='voting'?'is-live':''));var top=el('div');top.appendChild(el('small','',item.position+'º item · '+item.voteType));top.appendChild(el('h3','',item.matter.type+' nº '+item.matter.number+'/'+item.matter.year));top.appendChild(el('p','',item.matter.subject));card.appendChild(top);card.appendChild(el('strong','panel-result',item.status==='closed'?(item.result==='approved'?'APROVADA':item.result==='no_quorum'?'SEM QUÓRUM':'REJEITADA'):status(item.status)));card.appendChild(el('p','panel-tally',tally(item.tally)));agenda.appendChild(card);});if(!(data.agenda||[]).length)agenda.appendChild(el('p','panel-empty','Nenhuma matéria na pauta.'));
		var speakers=document.getElementById('panel-speakers');speakers.replaceChildren();(data.speakers||[]).filter(function(x){return x.status!=='done';}).forEach(function(x){var row=el('div','panel-speaker '+(x.status==='speaking'?'is-speaking':''));row.appendChild(el('strong','',x.displayName));row.appendChild(el('span','',x.status==='speaking'?'COM A PALAVRA':x.position+'º na fila'));if(x.topic)row.appendChild(el('small','',x.topic));speakers.appendChild(row);});if(!speakers.children.length)speakers.appendChild(el('p','panel-empty','Nenhum orador inscrito.'));}
	function updateTimer(){var out=document.getElementById('panel-timer');if(!timerState||timerState.status==='idle'||!timerState.duration){out.textContent='00:00';return;}var elapsed=timerState.status==='running'?Math.floor((timerState.server+(Date.now()-timerState.received)-new Date(timerState.started).getTime())/1000):0;var left=Math.max(0,timerState.duration-elapsed);out.textContent=String(Math.floor(left/60)).padStart(2,'0')+':'+String(left%60).padStart(2,'0');out.classList.toggle('is-expired',left===0);}
	function load(){if(loading)return;loading=true;var suffix=eventId?'?since='+encodeURIComponent(eventId):'';fetch(OC.generateUrl('/apps/legislativo/api/public/sessions/'+id)+suffix,{headers:{Accept:'application/json'},cache:'no-store'}).then(function(r){if(r.status===204)return null;return r.json().then(function(p){if(!r.ok)throw new Error(p.message||'Falha ao carregar painel.');return p;});}).then(function(p){if(!p)return;document.getElementById('panel-error').hidden=true;eventId=p.data.eventId||'';render(p.data);}).catch(function(e){var n=document.getElementById('panel-error');n.textContent=e.message;n.hidden=false;}).finally(function(){loading=false;});}
	setInterval(function(){document.getElementById('panel-clock').textContent=new Intl.DateTimeFormat('pt-BR',{timeStyle:'medium'}).format(new Date());updateTimer();},250);setInterval(load,1000);load();
}());
