<?php

declare(strict_types=1);

/**
 * SPDX-FileCopyrightText: 2026 LibreCode
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
return [
	'routes' => [
		['name' => 'dashboard#index', 'url' => '/', 'verb' => 'GET'],
		['name' => 'dashboard#health', 'url' => '/api/v1/health', 'verb' => 'GET'],
		['name' => 'audit#index', 'url' => '/api/v1/audit', 'verb' => 'GET'],
		['name' => 'matter#index', 'url' => '/api/v1/matters', 'verb' => 'GET'],
		['name' => 'matter#show', 'url' => '/api/v1/matters/{id}', 'verb' => 'GET'],
		['name' => 'matter#create', 'url' => '/api/v1/matters', 'verb' => 'POST'],
		['name' => 'matter#update', 'url' => '/api/v1/matters/{id}', 'verb' => 'PUT'],
		['name' => 'matter#protocol', 'url' => '/api/v1/matters/{id}/protocols', 'verb' => 'POST'],
		['name' => 'matter#proceed', 'url' => '/api/v1/matters/{id}/proceedings', 'verb' => 'POST'],
		['name' => 'matter#proceedBatch', 'url' => '/api/v1/matters/{id}/proceedings/batch', 'verb' => 'POST'],
		['name' => 'workflow#attach', 'url' => '/api/v1/matters/{id}/attachments', 'verb' => 'POST'],
		['name' => 'workflow#submissions', 'url' => '/api/v1/submissions', 'verb' => 'GET'],
		['name' => 'workflow#submit', 'url' => '/api/v1/submissions', 'verb' => 'POST'],
		['name' => 'workflow#decide', 'url' => '/api/v1/submissions/{id}/decision', 'verb' => 'POST'],
		['name' => 'workflow#calendar', 'url' => '/api/v1/calendar', 'verb' => 'GET'],
		['name' => 'workflow#createCalendar', 'url' => '/api/v1/calendar', 'verb' => 'POST'],
		['name' => 'workflow#toggleCalendar', 'url' => '/api/v1/calendar/{id}', 'verb' => 'PUT'],
		['name' => 'workflow#deadlines', 'url' => '/api/v1/deadlines', 'verb' => 'GET'],
		['name' => 'workflow#completeProceeding', 'url' => '/api/v1/proceedings/{id}', 'verb' => 'PUT'],
		['name' => 'document#prepare', 'url' => '/api/v1/matters/{id}/documents', 'verb' => 'POST'],
		['name' => 'document#requestSignature', 'url' => '/api/v1/matters/{id}/documents/{flowId}/signature', 'verb' => 'POST'],
		['name' => 'voting#index', 'url' => '/api/v1/sessions', 'verb' => 'GET'],
		['name' => 'voting#show', 'url' => '/api/v1/sessions/{id}', 'verb' => 'GET'],
		['name' => 'voting#create', 'url' => '/api/v1/sessions', 'verb' => 'POST'],
		['name' => 'voting#attendance', 'url' => '/api/v1/sessions/{id}/attendance', 'verb' => 'POST'],
		['name' => 'voting#addAgenda', 'url' => '/api/v1/sessions/{id}/agenda', 'verb' => 'POST'],
		['name' => 'voting#transition', 'url' => '/api/v1/sessions/{id}/transition', 'verb' => 'POST'],
		['name' => 'voting#transitionBallot', 'url' => '/api/v1/sessions/{id}/agenda/{itemId}/transition', 'verb' => 'POST'],
		['name' => 'voting#cast', 'url' => '/api/v1/sessions/{id}/agenda/{itemId}/votes', 'verb' => 'POST'],
		['name' => 'voting#requestSpeech', 'url' => '/api/v1/sessions/{id}/speakers', 'verb' => 'POST'],
		['name' => 'voting#transitionSpeaker', 'url' => '/api/v1/sessions/{id}/speakers/{speakerId}/transition', 'verb' => 'POST'],
		['name' => 'voting#timer', 'url' => '/api/v1/sessions/{id}/timer', 'verb' => 'POST'],
		['name' => 'parliamentarian#index', 'url' => '/api/v1/parliamentarians', 'verb' => 'GET'],
		['name' => 'parliamentarian#save', 'url' => '/api/v1/parliamentarians', 'verb' => 'POST'],
		['name' => 'sessionDocument#generate', 'url' => '/api/v1/sessions/{id}/documents', 'verb' => 'POST'],
		['name' => 'sessionDocument#saveMinutes', 'url' => '/api/v1/sessions/{id}/minutes', 'verb' => 'POST'],
		['name' => 'sessionDocument#requestMinutesSignature', 'url' => '/api/v1/sessions/{id}/minutes/signature', 'verb' => 'POST'],
		['name' => 'publicPanel#page', 'url' => '/panel/{id}', 'verb' => 'GET'],
		['name' => 'publicPanel#data', 'url' => '/api/public/sessions/{id}', 'verb' => 'GET'],
		['name' => 'publicPortal#page', 'url' => '/portal', 'verb' => 'GET'],
		['name' => 'publicPortal#parliamentarianPage', 'url' => '/portal/parliamentarians/{id}', 'verb' => 'GET'],
		['name' => 'publicPortal#matters', 'url' => '/api/public/portal/matters', 'verb' => 'GET'],
		['name' => 'publicPortal#matter', 'url' => '/api/public/portal/matters/{id}', 'verb' => 'GET'],
		['name' => 'publicPortal#sessions', 'url' => '/api/public/portal/sessions', 'verb' => 'GET'],
		['name' => 'publicPortal#search', 'url' => '/api/public/portal/search', 'verb' => 'GET'],
		['name' => 'publicPortal#parliamentarians', 'url' => '/api/public/portal/parliamentarians', 'verb' => 'GET'],
		['name' => 'publicPortal#parliamentarian', 'url' => '/api/public/portal/parliamentarians/{id}', 'verb' => 'GET'],
		['name' => 'norm#index', 'url' => '/api/v1/norms', 'verb' => 'GET'],
		['name' => 'norm#show', 'url' => '/api/v1/norms/{id}', 'verb' => 'GET'],
		['name' => 'norm#create', 'url' => '/api/v1/norms', 'verb' => 'POST'],
		['name' => 'norm#update', 'url' => '/api/v1/norms/{id}', 'verb' => 'PUT'],
		['name' => 'norm#version', 'url' => '/api/v1/norms/{id}/versions', 'verb' => 'POST'],
		['name' => 'norm#updateVersion', 'url' => '/api/v1/norms/versions/{versionId}', 'verb' => 'PUT'],
		['name' => 'norm#import', 'url' => '/api/v1/norms/import', 'verb' => 'POST'],
		['name' => 'norm#relation', 'url' => '/api/v1/norms/{id}/relations', 'verb' => 'POST'],
		['name' => 'publicNorm#index', 'url' => '/api/public/portal/norms', 'verb' => 'GET'],
		['name' => 'publicNorm#show', 'url' => '/api/public/portal/norms/{id}', 'verb' => 'GET'],
	],
];
